pbfgen:
  public: false
  formats: [pbf]
  uri: bridge://
  xml:
    npm: ["osm-bright-source", "data.xml"]
  xmlSetDataSource:
    if:
      dbname: gis
      host: ''
      type: postgis
    set:
      host: {var: osmdb-host}
      port: {var: osmdb-port}
      user: {var: osmdb-user}
      password: {var: osmdb-pass}
      dbname: {var: osmdb-dbname}

pbfstore:
  public: false
  formats: [pbf]
  uri: cassandra://
  params:
    keyspace: v1
    cp: [{var: cassandra-host }]
    createIfMissing: true

autogenpbf:
  public: false
  formats: [pbf]
  uri: autogen://
  params:
    storage: {ref: pbfstore}
    generator: {ref: pbfgen}
    mingen: 0
    maxgen: 12
    minstore: 0
    maxstore: 12

default:
  public: true
  formats: [png]
  uri: vector://
  xml:
    loader: osm-bright-style
  xmlSetParams:
    source: {ref: autogenpbf}
